### ISSUE TITLE
Add style checks

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#3]
This should probably be done via flake8 and github actions.

**Comment by ibLeDy** [comment]
Hi, i would like to work on this issue.

**Comment by TAG-Epic** [comment]
Hey! Thanks for wanting to help out!
I assigned you to the issue.

**Comment by ibLeDy** [comment]
Great, thanks!

Do you want me to add the check for multiple versions or just for one in particular?

I would like to point out that the check will run for `push` and `pull requests`, unless you say otherwise, of course.

**Comment by TAG-Epic** [comment]
I'm not sure what you mean by versions here.

Although yeah running on push and pr would be optimal

**Comment by ibLeDy** [comment]
Oh i meant python versions, i see that you specified ">=3.7" on your `setup.py` so i guess checking against `3.7` and `3.8` would be appropiate.

**Comment by TAG-Epic** [comment]
Sounds good!

**Comment by ibLeDy** [comment]
Perfect, i'll have the PR ready in a bit.

As a heads up, most of flake8's complaints about this repo are about lines too long (flake8 uses `79` as it's `max-line-length` by default). In some cases you do want to keep the lines as they are, so i would recommend two solutions, either ignoring the specific error (E501 in this case) or setting a custom `max-line-length`. I could absolutely fix it for you if you _do_ want any of those solutions.

A common alternative is to use a tool like `black` or `autopep8` which will auto format the code to follow common conventions. The only needed configuration would be to set a common `line-length`, as an example i use black's default one (`88`), so i configure flake8 to use the same, otherwise one would set black to the line-length that flake8 uses by default, or configure both to a custom value. 

I could also set this up so it formats the code before flake8's checks and most of the common errors would be fixed automatically.

The first two solutions (flake8's configuration) would be the less disruptive although the build would fail easily and you would have to fix and commit again.

Please let me know if you want me to set up any of this. Otherwise sorry for the vast amount of text :sob:

**Comment by TAG-Epic** [comment]
Hmm yeah setting a max line length sounds like a good idea. Generally I like to follow PyCharms codestyle so 120 chars sounds like a good idea.

Autoformatting... hmm yes it sounds good but a lot can fail like if they have disabled allow edits by maintainers would make it fail. If there was a possibility to use pycharms cli formatter for this that would be neat, although that looks hard so something like autoflake8 might work

**Comment by ibLeDy** [comment]
Okey, will set it to flake8 120, and i think you're right about the permissions, so i won't set up the autoformatter.
